version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
